### ISSUE TITLE
Set DJANGO_HOST_PROTOCOL to https if tls is enabled

### ISSUE THREAD

**Issue by hairmare** [adfinis-sygroup/timed-chart#17]
The `DJANGO_HOST_PROTOCOL` env should *probably* be set to `https` if tls is enabled on the ingress.

https://github.com/adfinis-sygroup/timed-chart/blob/14df5e445a41eac9e7a3c5c90f41f384a5538adf/charts/timed/templates/configmap-backend.yaml#L12

**Comment by strixBE** [comment]
Not sure. The traffic that reaches Django is http anyways, TLS is terminated on the ingress controller.

**Comment by strixBE** [comment]
Host protocol is used by timed to create valid links in emails: https://github.com/adfinis-sygroup/timed-backend/blob/0e11570e164ddbb684c7a45e530b89f549f7b94e/timed/reports/management/commands/notify_reviewers_unverified.py#L115
