### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by strixBE** [adfinis-sygroup/timed-chart#21]
**Describe the bug**
`README.md` is outdated and should be adapted to the new chart version

**Comment by strixBE** [comment]
Other repos list all parameters in README (i.e. https://github.com/helm/charts/tree/master/stable/wordpress#parameters) 
I think it's more useful to have a reasonably documented `values.yaml`. Should we add a table?

**Comment by hairmare** [comment]
There should also be some info on how to use the published chart repo.
