### ISSUE TITLE
Create test data for simple quickstart

### ISSUE THREAD

**Issue by sliverc** [adfinis-sygroup/timed-chart#5]
When installed with helm at the beginning data needs to be added (Customers, Projects, Tasks) in Django Admin before Timed can really be used.

For simple testing it would be desired though to have some quickstart data. Could potentially be in a json file and loaded in container with ./manage.py loadjson or similar.

**Comment by strixBE** [comment]
test data can be loaded manually. in the container execute:
```
/app$ curl -O https://raw.githubusercontent.com/adfinis-sygroup/timed-backend/master/timed/fixtures/test_data.json
/app$ ./manage.py loaddata /app/test_data.json
```
